#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_powerdns="0.0.1"
  jq -n --arg powerdns "$ver_powerdns" '{powerdns: $powerdns}'
}

version "$@"
